# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 278249b19bad346648896cdc8541532c6813100baa7d92fbe6c852af541992447ff477b0b257a31b0a179985287f3188448686e10c69a6864d4bce46ccec06f4

test:
  secret_key_base: 40dccf825f45e5beb865d9105a55cf8d089cdb21b68dea9950a5f439a6864339b291bd779a2f50a6a56410ded564c46d6aa7c0f639f1ef416d8cc3744131a0bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
